language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jamesstarjohnson/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true jamesstarjohnson/react-docker npm run test
